version: '2'
services:
  apache:
#    image: rafaelcgstz/magento2
    build:
      context: .
      dockerfile: build/apache/Dockerfile
    ports:
      - "80:80" # web
      - "9001:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - ./src:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - magento2-network

  db:
    image: mariadb
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - magento2-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8080:80
    networks:
      - magento2-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - magento2-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - magento2-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magento2-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8081:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/storage:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretkey
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - CLUSTERED=true
    networks:
      - magento2-network

  elasticsearch:
    image: elasticsearch:7.6.0
#    build:
#      context: .
#      dockerfile: build/elasticsearch/Dockerfile
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=node-1
      - cluster.initial_master_nodes=node-1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - magento2-network

networks:
  magento2-network:
    driver: bridge

volumes:
  dbdata:
    driver: local